const mongoose = require("mongoose");
const dotenv = require("dotenv");
dotenv.config();

const AptitudeQuestion = require("../models/AptitudeQuestion");

mongoose.connect(process.env.MONGO_URI)
  .then(() => console.log("MongoDB connected"))
  .catch(err => console.error(err));



const questionsJS = [
  { question: "Which keyword declares block-scoped variable?", options: ["let", "var", "const", "both"], answer: "let", techStack: "JavaScript" },
  { question: "Which method converts JSON to object?", options: ["JSON.parse", "JSON.stringify", "parseJSON", "toObject"], answer: "JSON.parse", techStack: "JavaScript" },
  { question: "Which operator checks equality without type coercion?", options: ["===", "==", "!=", "!=="], answer: "===", techStack: "JavaScript" },
  { question: "Which function converts string to integer?", options: ["parseInt", "Number", "int", "Both"], answer: "Both", techStack: "JavaScript" },
  { question: "Which keyword defines constant?", options: ["const", "let", "var", "define"], answer: "const", techStack: "JavaScript" },
  { question: "Which method adds element at the end of array?", options: ["push", "pop", "shift", "unshift"], answer: "push", techStack: "JavaScript" },
  { question: "Which loop iterates array elements?", options: ["for", "while", "foreach", "All"], answer: "All", techStack: "JavaScript" },
  { question: "Which object stores key-value pairs?", options: ["Map", "Object", "Both", "Set"], answer: "Both", techStack: "JavaScript" },
  { question: "Which operator increments value by 1?", options: ["++", "+=", "+=", "--"], answer: "++", techStack: "JavaScript" },
  { question: "Which method removes last element from array?", options: ["pop", "shift", "splice", "remove"], answer: "pop", techStack: "JavaScript" },
  { question: "Which type is not primitive?", options: ["Object", "Number", "Boolean", "String"], answer: "Object", techStack: "JavaScript" },
  { question: "Which keyword handles errors?", options: ["try", "catch", "throw", "All"], answer: "All", techStack: "JavaScript" },
  { question: "Which method joins array elements?", options: ["join", "concat", "append", "combine"], answer: "join", techStack: "JavaScript" },
  { question: "Which keyword exits loop?", options: ["break", "continue", "exit", "stop"], answer: "break", techStack: "JavaScript" },
  { question: "Which operator concatenates strings?", options: ["+", "&", "concat", "."], answer: "+", techStack: "JavaScript" },
  { question: "Which method converts object to JSON?", options: ["JSON.stringify", "JSON.parse", "toJSON", "toString"], answer: "JSON.stringify", techStack: "JavaScript" },
  { question: "Which type represents floating number?", options: ["Number", "Float", "Double", "All"], answer: "Number", techStack: "JavaScript" },
  { question: "Which keyword defines class?", options: ["class", "object", "struct", "function"], answer: "class", techStack: "JavaScript" },
  { question: "Which operator checks type?", options: ["typeof", "instanceof", "type", "kindof"], answer: "typeof", techStack: "JavaScript" },
  { question: "Which method adds element at start of array?", options: ["unshift", "push", "splice", "append"], answer: "unshift", techStack: "JavaScript" },
  { question: "Which keyword defines function?", options: ["function", "fun", "def", "lambda"], answer: "function", techStack: "JavaScript" },
  { question: "Which operator returns remainder?", options: ["%", "/", "*", "**"], answer: "%", techStack: "JavaScript" },
  { question: "Which function parses string to float?", options: ["parseFloat", "Number", "Float", "toFloat"], answer: "parseFloat", techStack: "JavaScript" },
  { question: "Which event triggers after page load?", options: ["onload", "onclick", "onready", "onchange"], answer: "onload", techStack: "JavaScript" },
  { question: "Which statement evaluates multiple conditions?", options: ["switch", "if", "for", "while"], answer: "switch", techStack: "JavaScript" },
  { question: "Which method finds index in array?", options: ["indexOf", "findIndex", "search", "find"], answer: "indexOf", techStack: "JavaScript" },
  { question: "Which method removes first element from array?", options: ["shift", "pop", "splice", "remove"], answer: "shift", techStack: "JavaScript" },
  { question: "Which keyword continues loop to next iteration?", options: ["continue", "break", "next", "skip"], answer: "continue", techStack: "JavaScript" },
  { question: "Which method checks if array includes element?", options: ["includes", "contains", "has", "indexOf"], answer: "includes", techStack: "JavaScript" }
];


const questionsPython = [
  { question: "Which keyword is used to define a function?", options: ["def", "function", "fun", "lambda"], answer: "def", techStack: "python" },
  { question: "What is the output of 3//2?", options: ["1", "1.5", "2", "0"], answer: "1", techStack: "python" },
  { question: "Which method adds an element to a list?", options: ["append", "add", "push", "insert"], answer: "append", techStack: "python" },
  { question: "What is the type of [1,2,3]?", options: ["list", "tuple", "set", "dict"], answer: "list", techStack: "python" },
  { question: "Which keyword is used for exception handling?", options: ["try", "catch", "handle", "except"], answer: "try", techStack: "python" },
  { question: "Which is used for multiline comment?", options: ["'''", "//", "/* */", "\"\"\""], answer: "'''", techStack: "python" },
  { question: "How to import math module?", options: ["import math", "include math", "use math", "from math import *"], answer: "import math", techStack: "python" },
  { question: "What is the output of bool('False')?", options: ["True", "False", "Error", "None"], answer: "True", techStack: "python" },
  { question: "Which keyword is used to create a class?", options: ["class", "struct", "object", "type"], answer: "class", techStack: "python" },
  { question: "How to create a set?", options: ["{1,2,3}", "[1,2,3]", "(1,2,3)", "set[1,2,3]"], answer: "{1,2,3}", techStack: "python" },
  { question: "How to remove last element from list?", options: ["pop", "remove", "del", "discard"], answer: "pop", techStack: "python" },
  { question: "Which keyword defines anonymous function?", options: ["lambda", "fun", "def", "anon"], answer: "lambda", techStack: "python" },
  { question: "Which is mutable?", options: ["list", "tuple", "str", "int"], answer: "list", techStack: "python" },
  { question: "What is output of 2**3?", options: ["8", "6", "9", "5"], answer: "8", techStack: "python" },
  { question: "Which function returns type?", options: ["type()", "typeof()", "class()", "kindof()"], answer: "type()", techStack: "python" },
  { question: "How to convert string '123' to integer?", options: ["int('123')", "str('123')", "parseInt('123')", "float('123')"], answer: "int('123')", techStack: "python" },
  { question: "Which function reads input from user?", options: ["input", "read", "scanf", "cin"], answer: "input", techStack: "python" },
  { question: "Which keyword is used to inherit a class?", options: ["class Derived(Base)", "extends", "inherits", "implements"], answer: "class Derived(Base)", techStack: "python" },
  { question: "Which method removes item from set?", options: ["discard", "remove", "pop", "delete"], answer: "discard", techStack: "python" },
  { question: "What is the output of len('Hello')?", options: ["5", "4", "6", "Error"], answer: "5", techStack: "python" },
  { question: "Which operator is for floor division?", options: ["//", "/", "%", "**"], answer: "//", techStack: "python" },
  { question: "How to open a file for reading?", options: ["open('file.txt','r')", "read('file.txt')", "file('file.txt')", "open('file.txt','w')"], answer: "open('file.txt','r')", techStack: "python" },
  { question: "Which keyword is used for iteration?", options: ["for", "while", "loop", "repeat"], answer: "for", techStack: "python" },
  { question: "Which method sorts list in place?", options: ["sort()", "sorted()", "order()", "arrange()"], answer: "sort()", techStack: "python" },
  { question: "Which function returns ASCII code of char?", options: ["ord()", "chr()", "ascii()", "code()"], answer: "ord()", techStack: "python" },
  { question: "Which function converts ASCII to character?", options: ["chr()", "ord()", "char()", "ascii()"], answer: "chr()", techStack: "python" },
  { question: "Which operator concatenates strings?", options: ["+", "&", "concat", "."], answer: "+", techStack: "python" },
  { question: "Which keyword exits loop immediately?", options: ["break", "continue", "exit", "stop"], answer: "break", techStack: "python" },
  { question: "Which is immutable data type?", options: ["tuple", "list", "dict", "set"], answer: "tuple", techStack: "python" },
  { question: "Which module is used for random numbers?", options: ["random", "math", "numbers", "rand"], answer: "random", techStack: "python" }
];


const questionsJava = [
  { question: "Which keyword is used to define a class?", options: ["class", "struct", "object", "define"], answer: "class", techStack: "java" },
  { question: "Which method is the entry point of Java program?", options: ["main()", "start()", "run()", "init()"], answer: "main()", techStack: "java" },
  { question: "Which keyword is used for inheritance?", options: ["extends", "implements", "inherits", "super"], answer: "extends", techStack: "java" },
  { question: "Which data type stores true/false?", options: ["boolean", "bool", "Boolean", "bit"], answer: "boolean", techStack: "java" },
  { question: "Which symbol is used to access class members?", options: [".", "->", "::", ":"], answer: ".", techStack: "java" },
  { question: "Which keyword prevents inheritance?", options: ["final", "static", "const", "private"], answer: "final", techStack: "java" },
  { question: "Which package is imported by default?", options: ["java.lang", "java.util", "java.io", "java.net"], answer: "java.lang", techStack: "java" },
  { question: "Which operator compares values?", options: ["==", "=", "equals", "compare"], answer: "==", techStack: "java" },
  { question: "Which keyword handles exceptions?", options: ["try", "catch", "throw", "All"], answer: "All", techStack: "java" },
  { question: "Which collection allows duplicates?", options: ["List", "Set", "Map", "None"], answer: "List", techStack: "java" },
  { question: "Which loop runs at least once?", options: ["do-while", "for", "while", "foreach"], answer: "do-while", techStack: "java" },
  { question: "Which class is used for input?", options: ["Scanner", "Input", "Reader", "Console"], answer: "Scanner", techStack: "java" },
  { question: "Which keyword creates object?", options: ["new", "create", "object", "init"], answer: "new", techStack: "java" },
  { question: "Which method converts String to int?", options: ["Integer.parseInt", "parseInt", "toInt", "convert"], answer: "Integer.parseInt", techStack: "java" },
  { question: "Which access modifier gives widest access?", options: ["public", "protected", "private", "default"], answer: "public", techStack: "java" },
  { question: "Which interface is used for list?", options: ["List", "Array", "Collection", "Map"], answer: "List", techStack: "java" },
  { question: "Which keyword is used to implement interface?", options: ["implements", "extends", "interface", "inherit"], answer: "implements", techStack: "java" },
  { question: "Which keyword refers to current object?", options: ["this", "self", "super", "current"], answer: "this", techStack: "java" },
  { question: "Which operator is logical AND?", options: ["&&", "&", "and", "||"], answer: "&&", techStack: "java" },
  { question: "Which class is parent of all classes?", options: ["Object", "Class", "Main", "Base"], answer: "Object", techStack: "java" },
  { question: "Which method prints output?", options: ["System.out.println", "print", "echo", "display"], answer: "System.out.println", techStack: "java" },
  { question: "Which keyword defines constant?", options: ["final", "const", "static", "immutable"], answer: "final", techStack: "java" },
  { question: "Which collection does not allow duplicates?", options: ["Set", "List", "Array", "Vector"], answer: "Set", techStack: "java" },
  { question: "Which exception is unchecked?", options: ["NullPointerException", "IOException", "SQLException", "FileNotFound"], answer: "NullPointerException", techStack: "java" },
  { question: "Which keyword calls parent constructor?", options: ["super", "this", "parent", "base"], answer: "super", techStack: "java" },
  { question: "Which method checks equality of objects?", options: ["equals", "==", "compare", "match"], answer: "equals", techStack: "java" },
  { question: "Which keyword stops loop?", options: ["break", "continue", "exit", "stop"], answer: "break", techStack: "java" },
  { question: "Which keyword skips iteration?", options: ["continue", "break", "skip", "next"], answer: "continue", techStack: "java" },
  { question: "Which type stores decimal numbers?", options: ["float", "int", "char", "boolean"], answer: "float", techStack: "java" },
  { question: "Which block always executes?", options: ["finally", "catch", "try", "throw"], answer: "finally", techStack: "java" }
];


const questionsCPlusPlus = [
  { "question": "Which symbol is used for single line comment?", "options": ["//", "/*", "--", "#"], "answer": "//", techStack: "c++" },
  { "question": "Which keyword defines class?", "options": ["class", "struct", "object", "define"], "answer": "class", techStack: "c++" },
  { "question": "Which operator is used for pointer?", "options": ["*", "&", "->", "%"], "answer": "*", techStack: "c++" },
  { "question": "Which function prints output?", "options": ["cout", "printf", "print", "echo"], "answer": "cout", techStack: "c++" },
  { "question": "Which header is for input/output?", "options": ["iostream", "stdio.h", "math.h", "conio.h"], "answer": "iostream", techStack: "c++" },
  { "question": "Which keyword is for inheritance?", "options": ["public", "extends", "inherits", "base"], "answer": "public", techStack: "c++" },
  { "question": "Which operator is scope resolution?", "options": ["::", ".", "->", ":"], "answer": "::", techStack: "c++"},
  { "question": "Which keyword creates object dynamically?", "options": ["new", "malloc", "alloc", "create"], "answer": "new", techStack: "c++" },
  { "question": "Which loop runs at least once?", "options": ["do-while", "while", "for", "foreach"], "answer": "do-while", techStack: "c++" },
  { "question": "Which operator checks equality?", "options": ["==", "=", "!=", "==="], "answer": "==", techStack: "c++" },
  { "question": "Which keyword stops loop?", "options": ["break", "exit", "stop", "continue"], "answer": "break", techStack: "c++" },
  { "question": "Which keyword skips iteration?", "options": ["continue", "break", "next", "skip"], "answer": "continue", techStack: "c++" },
  { "question": "Which type stores true/false?", "options": ["bool", "boolean", "bit", "flag"], "answer": "bool", techStack: "c++" },
  { "question": "Which keyword defines constant?", "options": ["const", "final", "static", "let"], "answer": "const", techStack: "c++" },
  { "question": "Which operator is logical AND?", "options": ["&&", "&", "and", "||"], "answer": "&&", techStack: "c++" },
  { "question": "Which function returns length of string?", "options": ["length()", "size()", "len()", "count()"], "answer": "length()", techStack: "c++" },
  { "question": "Which keyword defines constructor?", "options": ["class name", "init", "construct", "new"], "answer": "class name", techStack: "c++" },
  { "question": "Which STL container allows duplicates?", "options": ["vector", "set", "map", "unordered_set"], "answer": "vector", techStack: "c++" },
  { "question": "Which container does not allow duplicates?", "options": ["set", "vector", "array", "list"], "answer": "set", techStack: "c++" },
  { "question": "Which operator gets address?", "options": ["&", "*", "->", "%"], "answer": "&", techStack: "c++" },
  { "question": "Which function reads input?", "options": ["cin", "scanf", "input", "read"], "answer": "cin", techStack: "c++" },
  { "question": "Which keyword is for namespace?", "options": ["namespace", "using", "include", "package"], "answer": "namespace", techStack: "c++" },
  { "question": "Which keyword handles exception?", "options": ["try", "catch", "throw", "All"], "answer": "All", techStack: "c++" },
  { "question": "Which operator increments value?", "options": ["++", "+=", "+", "--"], "answer": "++", techStack: "c++" },
  { "question": "Which keyword is for polymorphism?", "options": ["virtual", "override", "poly", "abstract"], "answer": "virtual", techStack: "c++" },
  { "question": "Which operator dereferences pointer?", "options": ["*", "&", "->", "::"], "answer": "*", techStack: "c++" },
  { "question": "Which header is for string?", "options": ["string", "cstring", "str", "text"], "answer": "string", techStack: "c++" },
  { "question": "Which keyword allocates memory?", "options": ["new", "malloc", "alloc", "reserve"], "answer": "new", techStack: "c++" },
  { "question": "Which keyword deallocates memory?", "options": ["delete", "free", "remove", "clear"], "answer": "delete", techStack: "c++" },
  { "question": "Which block always executes?", "options": ["finally", "catch", "try", "throw"], "answer": "finally", techStack: "c++" }
];

const questionsCSharp = [
  { "question": "Which keyword defines class?", "options": ["class", "struct", "object", "define"], "answer": "class",techStack: "csharp" },
  { "question": "Which method is entry point?", "options": ["Main", "Start", "Run", "Init"], "answer": "Main", techStack: "csharp" },
  { "question": "Which keyword is for inheritance?", "options": [" : ", "extends", "inherits", "implements"], "answer": " : ", techStack: "csharp" },
  { "question": "Which type stores true/false?", "options": ["bool", "boolean", "bit", "flag"], "answer": "bool", techStack: "csharp" },
  { "question": "Which symbol accesses members?", "options": [".", "->", "::", ":"], "answer": ".", techStack: "csharp" },
  { "question": "Which keyword prevents override?", "options": ["sealed", "final", "const", "static"], "answer": "sealed", techStack: "csharp" },
  { "question": "Which class prints output?", "options": ["Console", "Print", "System", "Output"], "answer": "Console", techStack: "csharp" },
  { "question": "Which keyword creates object?", "options": ["new", "create", "init", "object"], "answer": "new", techStack: "csharp" },
  { "question": "Which keyword handles exception?", "options": ["try", "catch", "throw", "All"], "answer": "All", techStack: "csharp" },
  { "question": "Which collection allows duplicates?", "options": ["List", "Set", "Dictionary", "None"], "answer": "List", techStack: "csharp" },
  { "question": "Which loop runs at least once?", "options": ["do-while", "while", "for", "foreach"], "answer": "do-while", techStack: "csharp" },
  { "question": "Which method converts string to int?", "options": ["int.Parse", "parseInt", "toInt", "convert"], "answer": "int.Parse", techStack: "csharp" },
  { "question": "Which access modifier is widest?", "options": ["public", "protected", "private", "internal"], "answer": "public", techStack: "csharp" },
  { "question": "Which keyword refers current object?", "options": ["this", "self", "base", "current"], "answer": "this", techStack: "csharp" },
  { "question": "Which operator is logical AND?", "options": ["&&", "&", "and", "||"], "answer": "&&", techStack: "csharp" },
  { "question": "Which keyword inherits class?", "options": [" : ", "extends", "inherits", "super"], "answer": " : ", techStack: "csharp" },
  { "question": "Which keyword defines constant?", "options": ["const", "final", "static", "readonly"], "answer": "const", techStack: "csharp" },
  { "question": "Which keyword stops loop?", "options": ["break", "continue", "exit", "stop"], "answer": "break", techStack: "csharp" },
  { "question": "Which keyword skips iteration?", "options": ["continue", "break", "skip", "next"], "answer": "continue", techStack: "csharp" },
  { "question": "Which type stores decimals?", "options": ["float", "int", "char", "bool"], "answer": "float", techStack: "csharp" },
  { "question": "Which block always executes?", "options": ["finally", "catch", "try", "throw"], "answer": "finally", techStack: "csharp" },
  { "question": "Which keyword calls parent constructor?", "options": ["base", "this", "super", "parent"], "answer": "base", techStack: "csharp" },
  { "question": "Which operator compares values?", "options": ["==", "=", "!=", "==="], "answer": "==", techStack: "csharp" },
  { "question": "Which collection does not allow duplicates?", "options": ["HashSet", "List", "Array", "Vector"], "answer": "HashSet", techStack: "csharp" },
  { "question": "Which keyword defines interface?", "options": ["interface", "class", "struct", "object"], "answer": "interface", techStack: "csharp" },
  { "question": "Which method prints line?", "options": ["Console.WriteLine", "print", "echo", "display"], "answer": "Console.WriteLine", techStack: "csharp" },
  { "question": "Which type represents character?", "options": ["char", "string", "int", "byte"], "answer": "char", techStack: "csharp" },
  { "question": "Which keyword defines struct?", "options": ["struct", "class", "object", "define"], "answer": "struct", techStack: "csharp" },
  { "question": "Which keyword exits method?", "options": ["return", "exit", "stop", "break"], "answer": "return", techStack: "csharp" },
  { "question": "Which namespace contains collections?", "options": ["System.Collections", "System.IO", "System.Net", "System.Text"], "answer": "System.Collections", techStack: "csharp" }
];

const questionsGo = [
  { "question": "Which keyword declares a variable?", "options": ["var", "let", "int", "define"], "answer": "var",techStack: "go" },
  { "question": "Which keyword defines a function?", "options": ["func", "function", "def", "fn"], "answer": "func", techStack: "go" },
  { "question": "Which package is used for printing?", "options": ["fmt", "io", "print", "console"], "answer": "fmt", techStack: "go" },
  { "question": "Which symbol is used for pointer?", "options": ["*", "&", "->", "%"], "answer": "*", techStack: "go" },
  { "question": "Which keyword creates goroutine?", "options": ["go", "thread", "async", "run"], "answer": "go", techStack: "go" },
  { "question": "Which loop exists in Go?", "options": ["for", "while", "do", "foreach"], "answer": "for", techStack: "go" },
  { "question": "Which type stores true/false?", "options": ["bool", "boolean", "bit", "flag"], "answer": "bool", techStack: "go" },
  { "question": "Which keyword is for struct?", "options": ["struct", "class", "object", "type"], "answer": "struct", techStack: "go" },
  { "question": "Which keyword defines interface?", "options": ["interface", "class", "struct", "type"], "answer": "interface", techStack: "go" },
  { "question": "Which function prints line?", "options": ["fmt.Println", "print", "echo", "console.log"], "answer": "fmt.Println", techStack: "go" },
  { "question": "Which keyword handles error?", "options": ["error", "try", "catch", "throw"], "answer": "error", techStack: "go" },
  { "question": "Which operator compares values?", "options": ["==", "=", "!=", "==="], "answer": "==",techStack: "go" },
  { "question": "Which keyword returns value?", "options": ["return", "exit", "stop", "break"], "answer": "return", techStack: "go" },
  { "question": "Which keyword imports package?", "options": ["import", "include", "require", "using"], "answer": "import", techStack: "go" },
  { "question": "Which keyword defines type alias?", "options": ["type", "alias", "define", "struct"], "answer": "type", techStack: "go" },
  { "question": "Which operator gets address?", "options": ["&", "*", "->", "%"], "answer": "&", techStack: "go" },
  { "question": "Which function reads input?", "options": ["fmt.Scan", "input", "scan", "read"], "answer": "fmt.Scan", techStack: "go" },
  { "question": "Which type stores decimals?", "options": ["float64", "int", "char", "bool"], "answer": "float64", techStack: "go" },
  { "question": "Which keyword creates map?", "options": ["make", "new", "map", "create"], "answer": "make", techStack: "go" },
  { "question": "Which keyword defers execution?", "options": ["defer", "delay", "wait", "later"], "answer": "defer", techStack: "go" },
  { "question": "Which keyword handles panic?", "options": ["recover", "catch", "handle", "panic"], "answer": "recover", techStack: "go" },
  { "question": "Which keyword stops loop?", "options": ["break", "continue", "exit", "stop"], "answer": "break", techStack: "go" },
  { "question": "Which keyword skips iteration?", "options": ["continue", "break", "skip", "next"], "answer": "continue" , techStack: "go" },
  { "question": "Which operator increments value?", "options": ["++", "+=", "+", "--"], "answer": "++" , techStack: "go" },
  { "question": "Which type stores string?", "options": ["string", "char", "text", "str"], "answer": "string",  techStack: "go" },
  { "question": "Which keyword defines constant?", "options": ["const", "final", "static", "let"], "answer": "const", techStack: "go" },
  { "question": "Which keyword groups multiple declarations?", "options": ["var()", "group", "multi", "set"], "answer": "var()", techStack: "go" },
  { "question": "Which keyword defines channel?", "options": ["chan", "channel", "pipe", "stream"], "answer": "chan", techStack: "go" },
  { "question": "Which keyword closes channel?", "options": ["close", "end", "finish", "stop"], "answer": "close", techStack: "go" },
  { "question": "Which operator sends data to channel?", "options": ["<-", "->", "=>", "<="], "answer": "<-", techStack: "go" }
];

const questionsRust = [
  { "question": "Which keyword declares variable?", "options": ["let", "var", "mut", "define"], "answer": "let" , techStack: "rust" },
  { "question": "Which keyword makes variable mutable?", "options": ["mut", "var", "const", "change"], "answer": "mut", techStack: "rust" },
  { "question": "Which keyword defines function?", "options": ["fn", "func", "def", "function"], "answer": "fn", techStack: "rust" },
  { "question": "Which macro prints output?", "options": ["println!", "print()", "echo", "log"], "answer": "println!", techStack: "rust" },
  { "question": "Which keyword defines struct?", "options": ["struct", "class", "object", "type"], "answer": "struct", techStack: "rust" },
  { "question": "Which keyword defines enum?", "options": ["enum", "struct", "type", "class"], "answer": "enum", techStack: "rust" },
  { "question": "Which keyword handles error?", "options": ["Result", "try", "catch", "handle"], "answer": "Result", techStack: "rust"  },
  { "question": "Which keyword defines constant?", "options": ["const", "let", "static", "final"], "answer": "const", techStack: "rust" },
  { "question": "Which keyword returns value?", "options": ["return", "exit", "stop", "break"], "answer": "return", techStack: "rust" },
  { "question": "Which keyword imports module?", "options": ["use", "import", "include", "require"], "answer": "use", techStack: "rust" },
  { "question": "Which type stores true/false?", "options": ["bool", "boolean", "bit", "flag"], "answer": "bool", techStack: "rust" },
  { "question": "Which operator compares values?", "options": ["==", "=", "!=", "=="], "answer": "==", techStack: "rust" },
  { "question": "Which keyword stops loop?", "options": ["break", "continue", "exit", "stop"], "answer": "break", techStack: "rust" },
  { "question": "Which keyword skips iteration?", "options": ["continue", "break", "skip", "next"], "answer": "continue", techStack: "rust" },
  { "question": "Which keyword handles pattern matching?", "options": ["match", "switch", "case", "if"], "answer": "match", techStack: "rust" },
  { "question": "Which type stores string?", "options": ["String", "char", "text", "str"], "answer": "String", techStack: "rust" },
  { "question": "Which keyword defines trait?", "options": ["trait", "interface", "class", "struct"], "answer": "trait", techStack: "rust" },
  { "question": "Which symbol is reference?", "options": ["&", "*", "->", "%"], "answer": "&", techStack: "rust" },
  { "question": "Which keyword creates vector?", "options": ["vec!", "array", "list", "vector"], "answer": "vec!", techStack: "rust" },
  { "question": "Which keyword handles panic?", "options": ["panic!", "throw", "error", "fail"], "answer": "panic!", techStack: "rust" },
  { "question": "Which keyword defines lifetime?", "options": ["'a", "life", "time", "scope"], "answer": "'a", techStack: "rust" },
  { "question": "Which keyword defines module?", "options": ["mod", "module", "pkg", "namespace"], "answer": "mod", techStack: "rust" },
  { "question": "Which operator dereferences pointer?", "options": ["*", "&", "->", "::"], "answer": "*", techStack: "rust" },
  { "question": "Which type stores decimal?", "options": ["f64", "int", "char", "bool"], "answer": "f64", techStack: "rust" },
  { "question": "Which keyword defines static variable?", "options": ["static", "const", "let", "var"], "answer": "static", techStack: "rust" },
  { "question": "Which keyword handles optional values?", "options": ["Option", "Maybe", "Null", "Optional"], "answer": "Option", techStack: "rust" },
  { "question": "Which keyword defines implementation?", "options": ["impl", "implements", "extends", "use"], "answer": "impl", techStack: "rust" },
  { "question": "Which keyword for closure?", "options": ["| |", "fn", "lambda", "closure"], "answer": "| |", techStack: "rust" },
  { "question": "Which keyword is unsafe block?", "options": ["unsafe", "danger", "raw", "risk"], "answer": "unsafe", techStack: "rust" },
  { "question": "Which function converts string to number?", "options": ["parse()", "toInt", "convert", "number"], "answer": "parse()", techStack: "rust" }
];

const questionsTypescript = [
  { "question": "TypeScript is superset of?", "options": ["JavaScript", "Java", "Python", "C++"], "answer": "JavaScript", techStack: "typescript" },
  { "question": "Which keyword defines type?", "options": ["type", "interface", "define", "struct"], "answer": "type", techStack: "typescript" },
  { "question": "Which keyword defines interface?", "options": ["interface", "class", "type", "struct"], "answer": "interface", techStack: "typescript" },
  { "question": "Which type allows any value?", "options": ["any", "unknown", "var", "all"], "answer": "any", techStack: "typescript" },
  { "question": "Which keyword defines class?", "options": ["class", "struct", "object", "define"], "answer": "class", techStack: "typescript" },
  { "question": "Which symbol is for optional property?", "options": ["?", "!*", "*", "&"], "answer": "?", techStack: "typescript" },
  { "question": "Which keyword makes variable constant?", "options": ["const", "let", "var", "final"], "answer": "const", techStack: "typescript" },
  { "question": "Which type is strict null check?", "options": ["null", "void", "never", "undefined"], "answer": "never", techStack: "typescript" },
  { "question": "Which keyword imports module?", "options": ["import", "require", "include", "using"], "answer": "import", techStack: "typescript" },
  { "question": "Which keyword exports module?", "options": ["export", "send", "share", "module"], "answer": "export", techStack: "typescript" },
  { "question": "Which operator compares values?", "options": ["===", "==", "=", "!=", "<"], "answer": "===", techStack: "typescript" },
  { "question": "Which type stores true/false?", "options": ["boolean", "bool", "bit", "flag"], "answer": "boolean", techStack: "typescript" },
  { "question": "Which keyword extends class?", "options": ["extends", "implements", "inherit", "super"], "answer": "extends", techStack: "typescript" },
  { "question": "Which keyword implements interface?", "options": ["implements", "extends", "inherit", "super"], "answer": "implements", techStack: "typescript" },
  { "question": "Which keyword defines enum?", "options": ["enum", "type", "const", "class"], "answer": "enum", techStack: "typescript" },
  { "question": "Which keyword handles error?", "options": ["try", "catch", "throw", "All"], "answer": "All", techStack: "typescript" },
  { "question": "Which keyword defines generic?", "options": ["<T>", "generic", "template", "type"], "answer": "<T>", techStack: "typescript" },
  { "question": "Which keyword defines readonly?", "options": ["readonly", "const", "static", "final"], "answer": "readonly", techStack: "typescript" },
  { "question": "Which type is safer than any?", "options": ["unknown", "any", "never", "void"], "answer": "unknown", techStack: "typescript" },
  { "question": "Which keyword defines namespace?", "options": ["namespace", "module", "space", "scope"], "answer": "namespace", techStack: "typescript" },
  { "question": "Which keyword skips iteration?", "options": ["continue", "break", "next", "skip"], "answer": "continue", techStack: "typescript" },
  { "question": "Which keyword stops loop?", "options": ["break", "continue", "stop", "exit"], "answer": "break", techStack: "typescript" },
  { "question": "Which type is function type?", "options": ["()=>void", "function", "fn", "method"], "answer": "()=>void", techStack: "typescript" },
  { "question": "Which operator spreads object?", "options": ["...", "..", ".", "*"], "answer": "...", techStack: "typescript" },
  { "question": "Which type means no return?", "options": ["void", "null", "never", "undefined"], "answer": "void", techStack: "typescript" },
  { "question": "Which keyword for decorator?", "options": ["@", "decorator", "meta", "tag"], "answer": "@", techStack: "typescript" },
  { "question": "Which keyword declares variable?", "options": ["let", "var", "const", "All"], "answer": "All", techStack: "typescript" },
  { "question": "Which method converts JSON?", "options": ["JSON.parse", "parse", "convert", "toJSON"], "answer": "JSON.parse", techStack: "typescript" },
  { "question": "Which type stores numbers?", "options": ["number", "int", "float", "decimal"], "answer": "number", techStack: "typescript" },
  { "question": "Which type assertion uses?", "options": ["as", "cast", "convert", "type"], "answer": "as", techStack: "typescript" }
];

const questionsKotlin = [
  { "question": "Kotlin runs on which platform?", "options": ["JVM", "CLR", "Python VM", "Node"], "answer": "JVM", techStack: "kotlin" },
  { "question": "Which keyword declares variable?", "options": ["var", "let", "const", "valvar"], "answer": "var", techStack: "kotlin" },
  { "question": "Which keyword declares constant?", "options": ["val", "const", "var", "final"], "answer": "val", techStack: "kotlin" },
  { "question": "Which function prints output?", "options": ["println()", "print()", "echo()", "console.log()"], "answer": "println()", techStack: "kotlin" },
  { "question": "Which keyword defines function?", "options": ["fun", "func", "def", "function"], "answer": "fun", techStack: "kotlin" },
  { "question": "Which type stores true/false?", "options": ["Boolean", "bool", "bit", "flag"], "answer": "Boolean", techStack: "kotlin" },
  { "question": "Which symbol is for null safety?", "options": ["?", "!", "*", "&"], "answer": "?", techStack: "kotlin" },
  { "question": "Which keyword defines class?", "options": ["class", "struct", "object", "type"], "answer": "class", techStack: "kotlin" },
  { "question": "Which keyword extends class?", "options": [":", "extends", "inherit", "super"], "answer": ":", techStack: "kotlin" },
  { "question": "Which keyword defines interface?", "options": ["interface", "class", "type", "struct"], "answer": "interface", techStack: "kotlin" },
  { "question": "Which keyword handles null pointer?", "options": ["?.", "!!", "?:", "All"], "answer": "All", techStack: "kotlin" },
  { "question": "Which keyword defines data class?", "options": ["data", "class", "object", "type"], "answer": "data", techStack: "kotlin" },
  { "question": "Which keyword imports package?", "options": ["import", "include", "require", "using"], "answer": "import", techStack: "kotlin" },
  { "question": "Which keyword handles exceptions?", "options": ["try", "catch", "throw", "All"], "answer": "All", techStack: "kotlin" },
  { "question": "Which operator compares values?", "options": ["==", "=", "!=", "==="], "answer": "==", techStack: "kotlin" },
  { "question": "Which keyword for inheritance restriction?", "options": ["open", "final", "sealed", "abstract"], "answer": "open", techStack: "kotlin" },
  { "question": "Which keyword defines singleton?", "options": ["object", "class", "single", "static"], "answer": "object", techStack: "kotlin" },
  { "question": "Which type stores numbers?", "options": ["Int", "Number", "Float", "Decimal"], "answer": "Int", techStack: "kotlin" },
  { "question": "Which keyword defines constructor?", "options": ["constructor", "init", "build", "create"], "answer": "constructor", techStack: "kotlin" },
  { "question": "Which keyword defines abstract class?", "options": ["abstract", "open", "sealed", "class"], "answer": "abstract", techStack: "kotlin" },
  { "question": "Which keyword is for loop?", "options": ["for", "while", "loop", "repeat"], "answer": "for", techStack: "kotlin" },
  { "question": "Which keyword stops loop?", "options": ["break", "stop", "exit", "continue"], "answer": "break", techStack: "kotlin" },
  { "question": "Which keyword skips iteration?", "options": ["continue", "break", "next", "skip"], "answer": "continue", techStack: "kotlin" },
  { "question": "Which keyword defines extension function?", "options": ["fun ClassName.func", "extend", "extension", "add"], "answer": "fun ClassName.func", techStack: "kotlin" },
  { "question": "Which type is nullable string?", "options": ["String?", "String!", "String*", "String&"], "answer": "String?", techStack: "kotlin" },
  { "question": "Which keyword defines companion object?", "options": ["companion", "object", "static", "inner"], "answer": "companion", techStack: "kotlin" },
  { "question": "Which keyword defines enum?", "options": ["enum", "type", "class", "const"], "answer": "enum", techStack: "kotlin" },
  { "question": "Which function converts string to int?", "options": ["toInt()", "parseInt()", "convert()", "int()"], "answer": "toInt()", techStack: "kotlin" },
  { "question": "Which keyword defines lambda?", "options": ["{ }", "lambda", "fn", "=>"], "answer": "{ }", techStack: "kotlin" },
  { "question": "Which keyword defines visibility?", "options": ["public", "private", "protected", "All"], "answer": "All", techStack: "kotlin" }
];

const questionsSwift = [
  { "question": "Swift is developed by?", "options": ["Apple", "Google", "Microsoft", "IBM"], "answer": "Apple" , techStack: "swift"},
  { "question": "Which keyword declares variable?", "options": ["var", "let", "const", "define"], "answer": "var", techStack: "swift" },
  { "question": "Which keyword declares constant?", "options": ["let", "const", "var", "final"], "answer": "let", techStack: "swift" },
  { "question": "Which function prints output?", "options": ["print()", "println()", "echo()", "console.log()"], "answer": "print()", techStack: "swift" },
  { "question": "Which keyword defines function?", "options": ["func", "function", "def", "fn"], "answer": "func", techStack: "swift" },
  { "question": "Which type stores true/false?", "options": ["Bool", "Boolean", "bit", "flag"], "answer": "Bool", techStack: 	"swift" },
  { "question": "Which symbol unwraps optional?", "options": ["!", "?", "*", "&"], "answer": "!", techStack: 	"swift" },
  { "question": "Which keyword defines class?", "options": ["class", "struct", "object", "type"], "answer": "class", techStack: "swift" },
  { "question": "Which keyword defines structure?", "options": ["struct", "class", "object", "type"], "answer": "struct", techStack: "swift" },
  { "question": "Which keyword defines enum?", "options": ["enum", "class", "struct", "type"], "answer": "enum", techStack: "swift" },
  { "question": "Which keyword handles error?", "options": ["do", "try", "catch", "All"], "answer": "All", techStack: 	"swift" },
  { "question": "Which operator compares values?", "options": ["==", "=", "!=", "==="], "answer": "==", techStack: 	"swift" },
  { "question": "Which keyword for inheritance?", "options": [":", "extends", "inherit", "super"], "answer": ":", techStack: 	"swift" },
  { "question": "Which keyword defines protocol?", "options": ["protocol", "interface", "class", "struct"], "answer": "protocol", techStack: "swift" },
  { "question": "Which type stores integers?", "options": ["Int", "Number", "Float", "Decimal"], "answer": "Int", techStack: "swift" },
  { "question": "Which keyword imports module?", "options": ["import", "include", "require", "using"], "answer": "import", techStack: "swift" },
  { "question": "Which keyword defines extension?", "options": ["extension", "extend", "add", "extra"], "answer": "extension", techStack: "swift" },
  { "question": "Which keyword handles nil value?", "options": ["?", "!", "nil", "All"], "answer": "All", techStack: "swift" },
  { "question": "Which keyword defines closure?", "options": ["{ }", "lambda", "fn", "=>"], "answer": "{ }", techStack: "swift" },
  { "question": "Which keyword defines constant group?", "options": ["let", "const", "group", "static"], "answer": "let", techStack: 	"swift" },
  { "question": "Which keyword defines optional?", "options": ["?", "!", "optional", "nil"], "answer": "?", techStack: 	"swift" },
  { "question": "Which keyword stops loop?", "options": ["break", "continue", "exit", "stop"], "answer": "break", techStack: "swift" },
  { "question": "Which keyword skips iteration?", "options": ["continue", "break", "next", "skip"], "answer": "continue", techStack: "swift" },
  { "question": "Which keyword defines initializer?", "options": ["init", "constructor", "build", "create"], "answer": "init", techStack: 	"swift" },
  { "question": "Which keyword defines deinitializer?", "options": ["deinit", "destroy", "delete", "remove"], "answer": "deinit", techStack: 	"swift" },
  { "question": "Which keyword defines access control?", "options": ["public", "private", "internal", "All"], "answer": "All", techStack: 	"swift" },
  { "question": "Which keyword defines guard statement?", "options": ["guard", "check", "if", "validate"], "answer": "guard", techStack: "swift" },
  { "question": "Which function converts string to int?", "options": ["Int()", "parseInt()", "convert()", "int()"], "answer": "Int()", techStack: "swift" },
  { "question": "Which keyword defines static method?", "options": ["static", "class", "const", "fixed"], "answer": "static", techStack: 	"swift" },
  { "question": "Which type is double precision?", "options": ["Double", "Float", "Decimal", "Number"], "answer": "Double", techStack: 	"swift" }
];

const questionsHtml = [
  { "question": "What does HTML stand for?", "options": ["Hyper Trainer Marking Language", "Hyper Text Marketing Language", "Hyper Text Markup Language", "Hyper Tool Multi Language"], "answer": "Hyper Text Markup Language", techStack: "html" },
  { "question": "Tag for hyperlink?", "options": ["<link>", "<a>", "<href>", "<url>"], "answer": "<a>", techStack: "html" },
  { "question": "Attribute for link URL?", "options": ["src", "href", "link", "url"], "answer": "href", techStack: "html" },
  { "question": "Image tag?", "options": ["<img>", "<image>", "<pic>", "<src>"], "answer": "<img>", techStack: "html" },
  { "question": "Line break tag?", "options": ["<lb>", "<br>", "<break>", "<newline>"], "answer": "<br>", techStack: "html" },
  { "question": "Largest heading tag?", "options": ["<h6>", "<h1>", "<head>", "<heading>"], "answer": "<h1>", techStack: 	"html" },
  { "question": "Unordered list tag?", "options": ["<ul>", "<ol>", "<li>", "<list>"], "answer": "<ul>", techStack: "html" },
  { "question": "Ordered list tag?", "options": ["<ol>", "<ul>", "<li>", "<order>"], "answer": "<ol>", techStack: "html" },
  { "question": "Table row tag?", "options": ["<td>", "<tr>", "<th>", "<row>"], "answer": "<tr>", techStack: "html" },
  { "question": "Table header cell?", "options": ["<td>", "<th>", "<tr>", "<thead>"], "answer": "<th>", techStack: "html" },
  { "question": "Form tag used for?", "options": ["Layout", "User input", "Image", "Style"], "answer": "User input", techStack: 	"html" },
  { "question": "Input type for password?", "options": ["text", "pass", "password", "secure"], "answer": "password", techStack: "html" },
  { "question": "Required attribute does?", "options": ["Validation", "Styling", "Layout", "Script"], "answer": "Validation", techStack: "html" },
  { "question": "Semantic tag for navigation?", "options": ["<nav>", "<menu>", "<header>", "<navigate>"], "answer": "<nav>", techStack: "html" },
  { "question": "<div> is?", "options": ["Inline", "Block", "Table", "List"], "answer": "Block", techStack: 	"html" },
  { "question": "Charset UTF-8 defines?", "options": ["Font", "Encoding", "Layout", "Style"], "answer": "Encoding", techStack: 	"html" },
  { "question": "Video tag?", "options": ["<video>", "<media>", "<movie>", "<vid>"], "answer": "<video>", techStack: "html" },
  { "question": "Audio tag?", "options": ["<audio>", "<sound>", "<music>", "<mp3>"], "answer": "<audio>", techStack: "html" },
  { "question": "alt attribute is for?", "options": ["Size", "Tooltip", "Alternative text", "Color"], "answer": "Alternative text", techStack: 	"html" },
  { "question": "Footer tag?", "options": ["<foot>", "<footer>", "<bottom>", "<end>"], "answer": "<footer>", techStack: 	"html" },
  { "question": "Open link in new tab?", "options": ["target='_self'", "target='_blank'", "new-tab", "open"], "answer": "target='_blank'", techStack: 	"html" },
  { "question": "Iframe used for?", "options": ["Video", "Embed page", "Form", "Audio"], "answer": "Embed page", techStack: "html" },
  { "question": "Dropdown tag?", "options": ["<select>", "<input>", "<list>", "<option>"], "answer": "<select>", techStack: "html" },
  { "question": "Group form fields?", "options": ["<group>", "<fieldset>", "<section>", "<formgroup>"], "answer": "<fieldset>", techStack: "html" },
  { "question": "Placeholder shows?", "options": ["Label", "Hint text", "Value", "Error"], "answer": "Hint text", techStack: 	"html" },
  { "question": "Script tag?", "options": ["<js>", "<script>", "<code>", "<javascript>"], "answer": "<script>", techStack: 	"html" },
  { "question": "Link CSS file?", "options": ["<style>", "<css>", "<link>", "<design>"], "answer": "<link>", techStack: "html" },
  { "question": "Doctype is for?", "options": ["Version declaration", "Style", "Script", "Layout"], "answer": "Version declaration", techStack: 	"html" },
  { "question": "<span> is?", "options": ["Block", "Inline", "Form", "Table"], "answer": "Inline", techStack: 	"html" },
  { "question": "HTML5 introduced?", "options": ["Semantic tags", "Tables", "Forms", "Images"], "answer": "Semantic tags", techStack: 	"html" }
];

const questionsCss = [
  { "question": "CSS stands for?", "options": ["Creative Style Sheets", "Cascading Style Sheets", "Colorful Style Sheets", "Computer Style Sheets"], "answer": "Cascading Style Sheets" , techStack: "css" },
  { "question": "ID selector symbol?", "options": [".", "#", "*", "@"], "answer": "#" , techStack: "css" },
  { "question": "Class selector symbol?", "options": [".", "#", "*", "&"], "answer": "." , techStack: "css" },
  { "question": "Text color property?", "options": ["text-color", "font-color", "color", "text-style"], "answer": "color" , techStack: "css" },
  { "question": "Background color property?", "options": ["bg-color", "background-color", "color-bg", "back-color"], "answer": "background-color" , techStack: "css" },
  { "question": "Margin is?", "options": ["Inside spacing", "Outside spacing", "Border", "Padding"], "answer": "Outside spacing" , techStack: 	"css" },
  { "question": "Padding is?", "options": ["Inside spacing", "Outside spacing", "Border", "Margin"], "answer": "Inside spacing" , techStack: 	"css" },
  { "question": "Bold text property?", "options": ["text-bold", "font-weight", "font-style", "text-weight"], "answer": "font-weight" , techStack: "css" },
  { "question": "Flexbox used for?", "options": ["Fonts", "Layout", "Colors", "Animation"], "answer": "Layout" , techStack: "css" },
  { "question": "display:none does?", "options": ["Hide but keep space", "Remove element", "Transparent", "Hidden only"], "answer": "Remove element" , techStack: 	"css" },
  { "question": "visibility:hidden keeps space?", "options": ["Yes", "No", "Sometimes", "Never"], "answer": "Yes" , techStack: 	"css" },
  { "question": "Default position?", "options": ["static", "relative", "absolute", "fixed"], "answer": "static" , techStack: 	"css" },
  { "question": "z-index controls?", "options": ["Size", "Stack order", "Color", "Position"], "answer": "Stack order" , techStack: "css" },
  { "question": "Make circle?", "options": ["border:round", "border-radius:50%", "shape:circle", "radius:100"], "answer": "border-radius:50%" , techStack: "css" },
  { "question": "Responsive design uses?", "options": ["Grid", "Media queries", "Flex", "Bootstrap"], "answer": "Media queries" , techStack: 	"css" },
  { "question": "text-shadow property?", "options": ["text-shadow", "box-shadow", "shadow", "font-shadow"], "answer": "text-shadow" , techStack: 	"css" },
  { "question": "box-shadow property?", "options": ["box-shadow", "shadow-box", "border-shadow", "text-shadow"], "answer": "box-shadow" , techStack: 	"css" },
  { "question": "Grid is?", "options": ["1D layout", "2D layout", "Animation", "Font tool"], "answer": "2D layout" , techStack: "css" },
  { "question": "Font size property?", "options": ["font-size", "text-size", "size", "font-style"], "answer": "font-size" , techStack: "css" },
  { "question": "Relative unit?", "options": ["px", "em", "cm", "pt"], "answer": "em" , techStack: 	"css" },
  { "question": "Transition property does?", "options": ["Move element", "Animate change", "Rotate", "Color"], "answer": "Animate change" , techStack: 	"css" },
  { "question": "Transform used for?", "options": ["Style", "Shape change", "Layout", "Font"], "answer": "Shape change" , techStack: 	"css" },
  { "question": "!important does?", "options": ["Ignore rule", "Highest priority", "Error", "Remove style"], "answer": "Highest priority" , techStack: "css" },
  { "question": "Overflow hidden means?", "options": ["Scroll", "Hide extra", "Stretch", "Shrink"], "answer": "Hide extra" , techStack: 	"css" },
  { "question": "Inline-block means?", "options": ["Block", "Inline", "Inline with size", "Hidden"], "answer": "Inline with size" , techStack: 	"css" },
  { "question": "Fixed position relative to?", "options": ["Parent", "Viewport", "Body", "Margin"], "answer": "Viewport" , techStack: 	"css" },
  { "question": "Absolute position relative to?", "options": ["Screen", "Parent positioned", "Body", "Margin"], "answer": "Parent positioned" , techStack: 	"css" },
  { "question": "Box-sizing border-box?", "options": ["Width excludes padding", "Width includes padding", "No border", "Content only"], "answer": "Width includes padding" , techStack: "css" },
  { "question": "Grid columns property?", "options": ["grid-columns", "grid-template-columns", "column-grid", "template-grid"], "answer": "grid-template-columns" , techStack: "css" },
  { "question": "CSS comment syntax?", "options": ["//", "<!-- -->", "/* */", "#"], "answer": "/* */" , techStack: 	"css" }
];

const questionsReact = [
  { "question": "React is a?", "options": ["Framework", "Library", "Language", "DB"], "answer": "Library" ,techStack: "react" },
  { "question": "JSX stands for?", "options": ["Java Syntax XML", "JavaScript XML", "JSON XML", "Java XML"], "answer": "JavaScript XML" , techStack: "react" },
  { "question": "useState is?", "options": ["API", "Hook", "Class", "Router"], "answer": "Hook" , techStack: "react" },
  { "question": "Props are?", "options": ["Mutable", "Read-only inputs", "State", "Hooks"], "answer": "Read-only inputs" , techStack: "react" },
  { "question": "State is?", "options": ["Static", "Mutable data", "Props", "Constant"], "answer": "Mutable data" , techStack: 	"react" },
  { "question": "Virtual DOM improves?", "options": ["Security", "Speed", "Design", "Routing"], "answer": "Speed" , techStack: 	"react" },
  { "question": "Key in list used for?", "options": ["Style", "Identify items", "Security", "Props"], "answer": "Identify items" , techStack: "react" },
  { "question": "useEffect used for?", "options": ["Routing", "Side effects", "Styling", "JSX"], "answer": "Side effects" , techStack: "react" },
  { "question": "Controlled component uses?", "options": ["DOM state", "React state", "Props", "Ref"], "answer": "React state" , techStack: 	"react" },
  { "question": "useRef used for?", "options": ["State", "DOM reference", "Routing", "API"], "answer": "DOM reference" , techStack: 	"react" },
  { "question": "Context API solves?", "options": ["Routing", "Prop drilling", "Styling", "API"], "answer": "Prop drilling" , techStack: 	"react" },
  { "question": "React Router used for?", "options": ["State", "Navigation", "Styling", "API"], "answer": "Navigation" , techStack: "react" },
  { "question": "Fragment avoids?", "options": ["Hooks", "Extra DOM", "Props", "State"], "answer": "Extra DOM" , techStack: 	"react" },
  { "question": "Lazy loading improves?", "options": ["Security", "Performance", "Styling", "State"], "answer": "Performance" , techStack: 	"react" },
  { "question": "Hooks used in?", "options": ["Classes", "Functions", "HTML", "CSS"], "answer": "Functions" , techStack: 	"react" },
  { "question": "Rule of hooks?", "options": ["Use anywhere", "Top-level only", "Loops", "Conditions"], "answer": "Top-level only" , techStack: 	"react" },
  { "question": "useMemo optimizes?", "options": ["API", "Expensive calc", "Routing", "Styling"], "answer": "Expensive calc" , techStack: "react" },
  { "question": "useCallback returns?", "options": ["Value", "Function", "JSX", "State"], "answer": "Function" , techStack: "react" },
  { "question": "Reconciliation is?", "options": ["Styling", "DOM diffing", "API", "Routing"], "answer": "DOM diffing" , techStack: 	"react" },
  { "question": "Redux used for?", "options": ["Styling", "Global state", "Routing", "Hooks"], "answer": "Global state" , techStack: 	"react" },
  { "question": "setState causes?", "options": ["API", "Re-render", "Style", "Route"], "answer": "Re-render" , techStack: 	"react" },
  { "question": "React maintained by?", "options": ["Google", "Meta", "Microsoft", "Amazon"], "answer": "Meta" , techStack: "react" },
  { "question": "JSX must return?", "options": ["Many roots", "One root", "Array", "String"], "answer": "One root" , techStack: 	"react" },
  { "question": "Functional components use?", "options": ["Classes", "Hooks", "DOM", "XML"], "answer": "Hooks" , techStack: 	"react" },
  { "question": "React DOM used for?", "options": ["Mobile", "Web", "Server", "CSS"], "answer": "Web" , techStack: 	"react" },
  { "question": "State updates are?", "options": ["Sync", "Async", "Static", "Slow"], "answer": "Async" , techStack: 	"react" },
  { "question": "Dependency array controls?", "options": ["Style", "Effect run", "Props", "DOM"], "answer": "Effect run" , techStack: 	"react" },
  { "question": "Default React start cmd?", "options": ["npm start", "node app", "react run", "start-react"], "answer": "npm start" , techStack: 	"react" },
  { "question": "HOC means?", "options": ["Hook", "Function returning component", "State", "DOM"], "answer": "Function returning component" , techStack: 	"react" },
  { "question": "Props drilling means?", "options": ["Routing", "Passing props deep", "Hook", "Style"], "answer": "Passing props deep" , techStack: 	"react" }
];


const questionsNodeJs = [
  { "question": "Node.js is built on?", "options": ["Chrome V8", "SpiderMonkey", "Java VM", "Python Engine"], "answer": "Chrome V8",techStack: "nodejs" },
  { "question": "Node.js is?", "options": ["Frontend", "Backend runtime", "Database", "OS"], "answer": "Backend runtime" , techStack: "nodejs" },
  { "question": "Module to create server?", "options": ["http", "fs", "url", "os"], "answer": "http" , techStack: "nodejs" },
  { "question": "File system module?", "options": ["file", "fs", "system", "path"], "answer": "fs" , techStack: "nodejs" },
  { "question": "npm stands for?", "options": ["Node Package Manager", "New Project Manager", "Node Program Method", "None"], "answer": "Node Package Manager" , techStack: 	"nodejs" },
  { "question": "require() used for?", "options": ["Import module", "Export module", "Run file", "Read file"], "answer": "Import module" , techStack: 	"nodejs" },
  { "question": "process.env stores?", "options": ["OS", "Env variables", "Files", "DB"], "answer": "Env variables" , techStack: 	"nodejs" },
  { "question": "Express is?", "options": ["Framework", "Library", "DB", "Engine"], "answer": "Framework" , techStack: 	"nodejs" },
  { "question": "Middleware runs?", "options": ["Before request", "After response", "During request-response", "Never"], "answer": "During request-response" , techStack: 	"nodejs" },
  { "question": "JSON.stringify does?", "options": ["Object to JSON", "JSON to object", "Print JSON", "Read JSON"], "answer": "Object to JSON" , techStack: 	"nodejs" },
  { "question": "Asynchronous means?", "options": ["Blocking", "Non-blocking", "Sync", "Fast"], "answer": "Non-blocking" , techStack: 	"nodejs" },
  { "question": "Callback is?", "options": ["Function as arg", "Loop", "Condition", "Variable"], "answer": "Function as arg" , techStack: 	"nodejs" },
  { "question": "Promise has states?", "options": ["1", "2", "3", "4"], "answer": "3", techStack: 	"nodejs" },
  { "question": "async/await used for?", "options": ["Loops", "Async code", "DB", "API"], "answer": "Async code" , techStack: 	"nodejs" },
  { "question": "res.send() sends?", "options": ["Request", "Response", "File", "JSON only"], "answer": "Response" , techStack: 	"nodejs" },
  { "question": "Port defined by?", "options": ["listen()", "run()", "start()", "open()"], "answer": "listen()" , techStack: 	"nodejs" },
  { "question": "Body parser used for?", "options": ["Parse body", "DB", "Auth", "Routing"], "answer": "Parse body" , techStack: 	"nodejs" },
  { "question": "REST stands for?", "options": ["Representational State Transfer", "Remote State Transfer", "Resource System", "None"], "answer": "Representational State Transfer" , techStack: 	"nodejs" },
  { "question": "JWT used for?", "options": ["Auth", "DB", "Style", "API"], "answer": "Auth" , techStack: 	"nodejs" },
  { "question": "CORS means?", "options": ["Cross-Origin Resource Sharing", "Code Origin", "Cross Server", "None"], "answer": "Cross-Origin Resource Sharing" , techStack: 	"nodejs" },
  { "question": "Event loop handles?", "options": ["DB", "Async tasks", "Files", "CSS"], "answer": "Async tasks" , techStack: 	"nodejs" },
  { "question": "__dirname gives?", "options": ["File name", "Directory path", "URL", "OS"], "answer": "Directory path" , techStack: 	"nodejs" },
  { "question": "fs.readFile is?", "options": ["Sync", "Async", "Loop", "JSON"], "answer": "Async" , techStack: 	"nodejs" },
  { "question": "nodemon does?", "options": ["Restart server", "Compile", "DB", "Style"], "answer": "Restart server" , techStack: 	"nodejs" },
  { "question": "package.json stores?", "options": ["Dependencies", "DB", "CSS", "HTML"], "answer": "Dependencies" , techStack: 	"nodejs" },
  { "question": "Router in Express used for?", "options": ["DB", "Routes", "Auth", "CSS"], "answer": "Routes" , techStack: 	"nodejs" },
  { "question": "res.status() sets?", "options": ["Header", "Status code", "Body", "Auth"], "answer": "Status code" , techStack: 	"nodejs" },
  { "question": "dotenv used for?", "options": ["Env config", "DB", "API", "Routing"], "answer": "Env config" , techStack: 	"nodejs" },
  { "question": "Buffer used for?", "options": ["Binary data", "JSON", "API", "CSS"], "answer": "Binary data" , techStack: 	"nodejs" },
  { "question": "Cluster module used for?", "options": ["Multi-core", "DB", "Routing", "Files"], "answer": "Multi-core" , techStack: 	"nodejs" }
];


const questionsSql = [
  { "question": "SQL stands for?", "options": ["Structured Query Language", "Simple Query Language", "System Query Language", "None"], "answer": "Structured Query Language" , techStack: "sql" },
  { "question": "Command to fetch data?", "options": ["GET", "SELECT", "FETCH", "READ"], "answer": "SELECT" , techStack: "sql" },
  { "question": "Insert data command?", "options": ["ADD", "INSERT", "PUT", "SET"], "answer": "INSERT" , techStack: "sql" },
  { "question": "Update data command?", "options": ["UPDATE", "MODIFY", "SET", "CHANGE"], "answer": "UPDATE" , techStack: "sql" },
  { "question": "Delete data command?", "options": ["REMOVE", "DELETE", "DROP", "CLEAR"], "answer": "DELETE" , techStack: 	"sql" },
  { "question": "Primary key is?", "options": ["Unique identifier", "Foreign key", "Index", "Constraint"], "answer": "Unique identifier" , techStack: 	"sql" },
  { "question": "Foreign key links?", "options": ["Table", "Column", "Tables", "Row"], "answer": "Tables" , techStack: 	"sql" },
  { "question": "WHERE used for?", "options": ["Filter", "Sort", "Join", "Group"], "answer": "Filter" , techStack: 	"sql" },
  { "question": "ORDER BY used for?", "options": ["Group", "Sort", "Filter", "Join"], "answer": "Sort" , techStack: 	"sql" },
  { "question": "COUNT() does?", "options": ["Sum", "Count rows", "Avg", "Max"], "answer": "Count rows" , techStack: 	"sql" },
  { "question": "JOIN combines?", "options": ["Rows", "Columns", "Tables", "DB"], "answer": "Tables" , techStack: 	"sql" },
  { "question": "INNER JOIN returns?", "options": ["All rows", "Matching rows", "Left rows", "Right rows"], "answer": "Matching rows" , techStack: 	"sql" },
  { "question": "GROUP BY used for?", "options": ["Filter", "Group rows", "Sort", "Join"], "answer": "Group rows" , techStack: 	"sql" },
  { "question": "HAVING used with?", "options": ["WHERE", "GROUP BY", "ORDER BY", "JOIN"], "answer": "GROUP BY" , techStack: 	"sql" },
  { "question": "LIKE used for?", "options": ["Pattern", "Math", "Join", "Filter"], "answer": "Pattern" , techStack: 	"sql" },
  { "question": "Wildcard symbol?", "options": ["%", "*", "_", "@"], "answer": "%" , techStack: 	"sql" },
  { "question": "ALTER used to?", "options": ["Delete table", "Modify table", "Insert row", "Join"], "answer": "Modify table" , techStack: 	"sql" },
  { "question": "DROP deletes?", "options": ["Row", "Column", "Table", "DB"], "answer": "Table" , techStack: 	"sql" },
  { "question": "CREATE used for?", "options": ["Table", "Row", "Join", "Group"], "answer": "Table" , techStack: 	"sql" },
  { "question": "Constraint for uniqueness?", "options": ["UNIQUE", "PRIMARY", "CHECK", "KEY"], "answer": "UNIQUE" , techStack: 	"sql" },
  { "question": "NULL means?", "options": ["Zero", "Empty", "No value", "False"], "answer": "No value" , techStack: 	"sql" },
  { "question": "Index improves?", "options": ["Security", "Speed", "Design", "Join"], "answer": "Speed" , techStack: 	"sql" },
  { "question": "BETWEEN used for?", "options": ["Range", "Join", "Sort", "Group"], "answer": "Range" , techStack: 	"sql" },
  { "question": "UNION combines?", "options": ["Rows", "Columns", "Tables", "DB"], "answer": "Rows" , techStack: 	"sql" },
  { "question": "DISTINCT removes?", "options": ["Duplicates", "Null", "Rows", "Columns"], "answer": "Duplicates" , techStack: 	"sql" },
  { "question": "AVG() returns?", "options": ["Sum", "Avg", "Max", "Count"], "answer": "Avg" , techStack: 	"sql" },
  { "question": "MAX() returns?", "options": ["Max value", "Min", "Sum", "Avg"], "answer": "Max value" , techStack: 	"sql" },
  { "question": "MIN() returns?", "options": ["Min value", "Max", "Sum", "Avg"], "answer": "Min value" , techStack: 	"sql" },
  { "question": "LIMIT used for?", "options": ["Restrict rows", "Filter", "Sort", "Join"], "answer": "Restrict rows" , techStack: 	"sql" },
  { "question": "Database create cmd?", "options": ["NEW DB", "CREATE DATABASE", "MAKE DB", "DB CREATE"], "answer": "CREATE DATABASE", techStack: 	"sql" }
];


const questionsNosql = [
  { "question": "MongoDB is?", "options": ["SQL DB", "NoSQL DB", "OS", "Language"], "answer": "NoSQL DB" ,techStack: "nosql" },
  { "question": "Data stored as?", "options": ["Tables", "Documents", "Rows", "Columns"], "answer": "Documents", techStack: "nosql" },
  { "question": "MongoDB uses?", "options": ["SQL", "BSON", "XML", "CSV"], "answer": "BSON" , techStack: "nosql" },
  { "question": "Insert command?", "options": ["add()", "insertOne()", "put()", "save()"], "answer": "insertOne()" , techStack: "nosql" },
  { "question": "Find data?", "options": ["search()", "find()", "get()", "fetch()"], "answer": "find()" , techStack: 	"nosql" },
  { "question": "Update data?", "options": ["modify()", "updateOne()", "change()", "set()"], "answer": "updateOne()" , techStack: 	"nosql" },
  { "question": "Delete data?", "options": ["deleteOne()", "remove()", "drop()", "clear()"], "answer": 	"deleteOne()" , techStack: 	"nosql" },
  { "question": "Collection is like?", "options": ["Table", "Row", "Column", "DB"], "answer": "Table" , techStack: 	"nosql" },
  { "question": "_id field is?", "options": ["Optional", "Primary key", "Foreign key", "Index"], "answer": "Primary key" , techStack: 	"nosql" },
  { "question": "Mongoose is?", "options": ["Driver", "ODM", "DB", "Framework"], "answer": "ODM" , techStack: 	"nosql" },
  { "question": "Schema defines?", "options": ["Structure", "DB", "Server", "Route"], "answer": "Structure" , techStack: 	"nosql" },
  { "question": "Aggregation used for?", "options": ["Complex queries", "Insert", "Delete", "Auth"], "answer": "Complex queries" , techStack: 	"nosql" },
  { "question": "$match stage does?", "options": ["Filter", "Join", "Sort", "Group"], "answer": "Filter", techStack: 	"nosql" },
  { "question": "$group stage does?", "options": ["Sort", "Group", "Filter", "Join"], "answer": "Group", techStack: 	"nosql" },
  { "question": "populate() does?", "options": ["Join", "Insert", "Delete", "Sort"], "answer": "Join", techStack: 	"nosql" },
  { "question": "NoSQL means?", "options": ["No structure", "Not only SQL", "No query", "None"], "answer": "Not only SQL", techStack: 	"nosql" },
  { "question": "Document size limit?", "options": ["16MB", "1MB", "64MB", "Unlimited"], "answer": "16MB", techStack: 	"nosql" },
  { "question": "Index improves?", "options": ["Speed", "Security", "Design", "Insert"], "answer": "Speed", techStack: 	"nosql" },
  { "question": "Atlas is?", "options": ["Tool", "Cloud DB", "Driver", "Framework"], "answer": "Cloud DB", techStack: 	"nosql" },
  { "question": "Projection means?", "options": ["Select fields", "Group", "Sort", "Filter"], "answer": "Select fields", techStack: 	"nosql" },
  { "question": "Embedded document means?", "options": ["Nested", "External", "SQL", "Join"], "answer": "Nested", techStack: 	"nosql" },
  { "question": "Replica set used for?", "options": ["Backup", "High availability", "Speed", "Insert"], "answer": "High availability", techStack: 	"nosql" },
  { "question": "Sharding used for?", "options": ["Scaling", "Security", "Auth", "Design"], "answer": "Scaling", techStack: 	"nosql" },
  { "question": "$sort stage does?", "options": ["Sort", "Filter", "Join", "Group"], "answer": "Sort", techStack: 	"nosql" },
  { "question": "$limit stage does?", "options": ["Limit", "Group", "Sort", "Filter"], "answer": "Limit", techStack: 	"nosql" },
  { "question": "findOne returns?", "options": ["One doc", "Many", "Array", "None"], "answer": "One doc", techStack: 	"nosql" },
  { "question": "drop() does?", "options": ["Delete collection", "Delete row", "Delete field", "None"], "answer": "Delete collection", techStack: 	"nosql" },
  { "question": "ObjectId is?", "options": ["ID type", "String", "Int", "Float"], "answer": "ID type", techStack: 	"nosql" },
  { "question": "Aggregation pipeline is?", "options": ["Stages", "Rows", "Tables", "Index"], "answer": "Stages", techStack: 	"nosql" },
  { "question": "Compass is?", "options": ["GUI tool", "Driver", "Framework", "Server"], "answer": "GUI tool", techStack: 	"nosql" }
];


const questionsAngular = [
  { "question": "Angular is developed by?", "options": ["Google", "Facebook", "Microsoft", "Apple"], "answer": "Google", techStack: 	"angular" },
  { "question": "Angular is written in?", "options": ["JavaScript", "TypeScript", "Python", "Java"], "answer": "TypeScript", techStack: 	"angular" },
  { "question": "Main building block?", "options": ["Module", "Component", "Service", "Directive"], "answer": "Component", techStack: 	"angular" },
  { "question": "Decorator for component?", "options": ["@NgModule", "@Component", "@Injectable", "@Directive"], "answer": "@Component", techStack: 	"angular" },
  { "question": "Two way binding syntax?", "options": ["[]", "()", "[()]", "{}"], "answer": "[()]", techStack: 	"angular" },
  { "question": "Service used for?", "options": ["UI", "Logic sharing", "Routing", "CSS"], "answer": "Logic sharing", techStack: 	"angular" },
  { "question": "ngFor used for?", "options": ["Loop", "Condition", "Style", "Route"], "answer": "Loop", techStack: 	"angular" },
  { "question": "ngIf used for?", "options": ["Loop", "Condition", "Route", "Style"], "answer": "Condition", techStack: 	"angular" },
  { "question": "RouterModule used for?", "options": ["API", "Routing", "DB", "Auth"], "answer": "Routing", techStack: 	"angular" },
  { "question": "HTTP requests via?", "options": ["HttpClient", "Axios", "Fetch", "Request"], "answer": "HttpClient", techStack: 	"angular" },
  { "question": "CLI command to create app?", "options": ["ng new", "ng create", "angular new", "app new"], "answer": "ng new", techStack: 	"angular" },
  { "question": "Directive changes?", "options": ["Behavior", "DB", "Server", "API"], "answer": "Behavior", techStack: 	"angular" },
  { "question": "Pipe used for?", "options": ["Transform data", "Route", "Auth", "API"], "answer": "Transform data", techStack: 	"angular" },
  { "question": "Dependency injection means?", "options": ["Provide services", "Routing", "Styling", "Loop"], "answer": "Provide services", techStack: 	"angular" },
  { "question": "Lifecycle hook example?", "options": ["ngOnInit", "init()", "start()", "onLoad()"], "answer": "ngOnInit", techStack: 	"angular" },
  { "question": "Module decorator?", "options": ["@Module", "@NgModule", "@Component", "@Inject"], "answer": "@NgModule", techStack: 	"angular" },
  { "question": "Angular uses MVC?", "options": ["Yes", "No", "Sometimes", "Optional"], "answer": "Yes", techStack: 	"angular" },
  { "question": "Forms module used for?", "options": ["Forms", "API", "Routing", "CSS"], "answer": "Forms", techStack: 	"angular" },
  { "question": "Reactive forms are?", "options": ["Model-driven", "Template-driven", "Static", "CSS"], "answer": "Model-driven", techStack: 	"angular" },
  { "question": "Event binding syntax?", "options": ["()", "[]", "{}", "<>"], "answer": "()", techStack: 	"angular" },
  { "question": "Property binding syntax?", "options": ["[]", "()","{}", "<>"], "answer": "[ ]", techStack: 	"angular" },
  { "question": "Angular version 2+ called?", "options": ["AngularJS", "Angular", "NgJS", "AJS"], "answer": "Angular", techStack: 	"angular" },
  { "question": "AngularJS is based on?", "options": ["JS", "TS", "Java", "C#"], "answer": "JS", techStack: 	"angular" },
  { "question": "Service decorator?", "options": ["@Injectable", "@Service", "@Provide", "@Use"], "answer": "@Injectable", techStack: 	"angular" },
  { "question": "Observable from?", "options": ["RxJS", "Redux", "Vuex", "Axios"], "answer": "RxJS", techStack: 	"angular" },
  { "question": "Async pipe used for?", "options": ["Observables", "Loop", "API", "CSS"], "answer": "Observables", techStack: 	"angular" },
  { "question": "Guard used for?", "options": ["Route protection", "DB", "Style", "Forms"], "answer": "Route protection", techStack: 	"angular" },
  { "question": "Angular architecture is?", "options": ["Component-based", "File-based", "MVC only", "API-based"], "answer": "Component-based", techStack: 	"angular" },
  { "question": "Template is?", "options": ["HTML", "CSS", "JS", "DB"], "answer": "HTML", techStack: 	"angular" },
  { "question": "Zone.js handles?", "options": ["Change detection", "Routing", "Forms", "API"], "answer": "Change detection", techStack: 	"angular" }
];


const questionsDjango = [
  { "question": "Django is written in?", "options": ["Python", "Java", "PHP", "C#"], "answer": "Python", techStack: 	"django" },
  { "question": "Django is?", "options": ["Framework", "Library", "DB", "Language"], "answer": "Framework", techStack: 	"django" },
  { "question": "Django follows?", "options": ["MVC", "MVT", "MVVM", "None"], "answer": "MVT", techStack: 	"django" },
  { "question": "ORM stands for?", "options": ["Object Relational Mapping", "Online Record Model", "Object Record Map", "None"], "answer": "Object Relational Mapping", techStack: 	"django" },
  { "question": "Command to create project?", "options": ["django start", "startproject", "django-admin startproject", "createproject"], "answer": "django-admin startproject", techStack: 	"django" },
  { "question": "App create command?", "options": ["startapp", "createapp", "newapp", "makeapp"], "answer": "startapp", techStack: 	"django" },
  { "question": "models.py stores?", "options": ["Models", "Views", "Routes", "Templates"], "answer": "Models", techStack: 	"django" },
  { "question": "views.py handles?", "options": ["Logic", "DB", "CSS", "Auth"], "answer": "Logic", techStack: 	"django" },
  { "question": "Template language?", "options": ["DTL", "HTML", "JS", "CSS"], "answer": "DTL", techStack: 	"django" },
  { "question": "Migration command?", "options": ["migrate", "makemigrations", "Both", "None"], "answer": "Both", techStack: 	"django" },
  { "question": "Admin panel built-in?", "options": ["Yes", "No", "Optional", "Plugin"], "answer": "Yes", techStack: 	"django" },
  { "question": "URL routing file?", "options": ["urls.py", "routes.py", "app.py", "path.py"], "answer": "urls.py", techStack: 	"django" },
  { "question": "manage.py used for?", "options": ["Commands", "DB", "CSS", "Auth"], "answer": "Commands", techStack: 	"django" },
  { "question": "Django DB default?", "options": ["SQLite", "MySQL", "PostgreSQL", "MongoDB"], "answer": "SQLite", techStack: 	"django" },
  { "question": "Superuser command?", "options": ["createsuperuser", "makeadmin", "newadmin", "setadmin"], "answer": "createsuperuser", techStack: 	"django" },
  { "question": "Static files used for?", "options": ["CSS/JS", "DB", "API", "Auth"], "answer": "CSS/JS", techStack: 	"django" },
  { "question": "Middleware handles?", "options": ["Request/Response", "DB", "CSS", "Auth"], "answer": "Request/Response", techStack: 	"django" },
  { "question": "CSRF protects from?", "options": ["Forgery", "SQLi", "XSS", "DOS"], "answer": "Forgery", techStack: 	"django" },
  { "question": "Template extends?", "options": ["Inheritance", "Loop", "Auth", "DB"], "answer": "Inheritance", techStack: 	"django" },
  { "question": "Context sends?", "options": ["Data to template", "DB", "CSS", "Auth"], "answer": "Data to template", techStack: 	"django" },
  { "question": "QuerySet returns?", "options": ["Objects", "Rows", "JSON", "None"], "answer": "Objects", techStack: 	"django" },
  { "question": "ForeignKey used for?", "options": ["Relations", "Loop", "Auth", "CSS"], "answer": "Relations", techStack: 	"django" },
  { "question": "settings.py contains?", "options": ["Config", "DB only", "Routes", "Views"], "answer": "Config", techStack: 	"django" },
  { "question": "WSGI stands for?", "options": ["Web Server Gateway Interface", "Web Server Global Interface", "None", "System Interface"], "answer": "Web Server Gateway Interface", techStack: 	"django" },
  { "question": "Django is secure by?", "options": ["Built-in features", "Plugin", "Manual", "None"], "answer": "Built-in features", techStack: 	"django" },
  { "question": "Paginator used for?", "options": ["Pagination", "Auth", "DB", "API"], "answer": "Pagination", techStack: 	"django" },
  { "question": "Signals used for?", "options": ["Events", "Routes", "CSS", "DB"], "answer": "Events", techStack: 	"django" },
  { "question": "Form validation built-in?", "options": ["Yes", "No", "Optional", "Plugin"], "answer": "Yes", techStack: 	"django" },
  { "question": "Django REST Framework is for?", "options": ["APIs", "DB", "CSS", "Auth"], "answer": "APIs", techStack: 	"django" },
  { "question": "Template tags are inside?", "options": ["{% %}", "{{ }}", "< >", "( )"], "answer": "{% %}", techStack: 	"django" }
];


const questionsSpring = [
  { "question": "Spring Boot is based on?", "options": ["Java", "Python", "C#", "JS"], "answer": "Java" ,techStack: "spring" },
  { "question": "Spring Boot used for?", "options": ["Backend", "Frontend", "DB", "CSS"], "answer": "Backend", techStack: "spring" },
  { "question": "Main annotation?", "options": ["@SpringBootApplication", "@App", "@Boot", "@Main"], "answer": "@SpringBootApplication", techStack: "spring" },
  { "question": "Dependency management via?", "options": ["Maven/Gradle", "npm", "pip", "composer"], "answer": "Maven/Gradle", techStack: "spring" },
  { "question": "REST controller annotation?", "options": ["@RestController", "@Controller", "@API", "@Request"], "answer": "@RestController", techStack: "spring" },
  { "question": "Autowired used for?", "options": ["DI", "Routing", "DB", "Auth"], "answer": "DI", techStack: 	"spring" },
  { "question": "Application config file?", "options": ["application.properties", "config.js", "settings.py", "app.json"], "answer": "application.properties", techStack: "spring" },
  { "question": "JPA stands for?", "options": ["Java Persistence API", "Java Program Access", "None", "Java API"], "answer": "Java Persistence API", techStack: "spring" },
  { "question": "Repository interface?", "options": ["JpaRepository", "DataRepo", "SQLRepo", "None"], "answer": "JpaRepository", techStack: 	"spring" },
  { "question": "@Entity defines?", "options": ["Table", "Class", "API", "Auth"], "answer": "Table", techStack: 	"spring" },
  { "question": "@GetMapping used for?", "options": ["GET API", "POST API", "PUT API", "DELETE API"], "answer": "GET API", techStack: 	"spring" },
  { "question": "@PostMapping used for?", "options": ["GET", "POST", "PUT", "DELETE"], "answer": "POST", techStack: "spring" },
  { "question": "Spring Boot embedded server?", "options": ["Tomcat", "Apache", "Nginx", "Node"], "answer": "Tomcat", techStack: "spring" },
  { "question": "application.yml is?", "options": ["Config file", "DB", "API", "Auth"], "answer": "Config file", techStack: 	"spring" },
  { "question": "Spring Security used for?", "options": ["Auth", "DB", "CSS", "Routing"], "answer": "Auth", techStack: 	"spring" },
  { "question": "Bean means?", "options": ["Managed object", "DB", "API", "Route"], "answer": "Managed object", techStack: 	"spring" },
  { "question": "IOC stands for?", "options": ["Inversion of Control", "Input Output Control", "None", "Internal Object Control"], "answer": "Inversion of Control", techStack: "spring" },
  { "question": "Spring Boot starter?", "options": ["Preconfigured deps", "DB", "CSS", "Auth"], "answer": "Preconfigured deps", techStack: "spring" },
  { "question": "@Service defines?", "options": ["Service layer", "DB", "API", "Auth"], "answer": "Service layer", techStack: 	"spring" },
  { "question": "@RequestBody used for?", "options": ["Read JSON", "Auth", "DB", "Route"], "answer": "Read JSON", techStack: 	"spring" },
  { "question": "@PathVariable used for?", "options": ["URL param", "Query", "Body", "Auth"], "answer": "URL param", techStack: 	"spring" },
  { "question": "Hibernate is?", "options": ["ORM", "DB", "Server", "CSS"], "answer": "ORM", techStack: "spring" },
  { "question": "Spring Boot Actuator used for?", "options": ["Monitoring", "Auth", "DB", "Routing"], "answer": "Monitoring", techStack: "spring" },
  { "question": "Microservices supported?", "options": ["Yes", "No", "Optional", "Plugin"], "answer": "Yes", techStack: 	"spring" },
  { "question": "@Component defines?", "options": ["Bean", "DB", "API", "Route"], "answer": "Bean", techStack: 	"spring" },
  { "question": "@Configuration defines?", "options": ["Config class", "DB", "API", "Auth"], "answer": "Config class", techStack: 	"spring" },
  { "question": "Spring Data used for?", "options": ["DB access", "Auth", "Routing", "CSS"], "answer": "DB access", techStack: "spring" },
  { "question": "DevTools used for?", "options": ["Auto restart", "DB", "CSS", "Auth"], "answer": "Auto restart", techStack: "spring" },
  { "question": "@ExceptionHandler handles?", "options": ["Errors", "Routes", "Auth", "DB"], "answer": "Errors", techStack: 	"spring" },
  { "question": "Spring Boot reduces?", "options": ["Boilerplate", "DB", "CSS", "Auth"], "answer": "Boilerplate", techStack: 	"spring" }
];


const questionsVue = [
  { "question": "Vue is a?", "options": ["JS Framework", "Database", "Language", "OS"], "answer": "JS Framework", techStack: "vue" },
  { "question": "Vue is used for?", "options": ["UI building", "Database", "AI", "Security"], "answer": "UI building", techStack: "vue" },
  { "question": "Vue instance created by?", "options": ["createApp()", "new VueApp()", "initVue()", "startVue()"], "answer": "createApp()", techStack: 	"vue" },
  { "question": "Directive to bind data?", "options": ["v-bind", "v-if", "v-for", "v-on"], "answer": "v-bind", techStack: 	"vue" },
  { "question": "Directive for loop?", "options": ["v-for", "v-if", "v-loop", "v-repeat"], "answer": "v-for", techStack: 	"vue" },
  { "question": "Directive for condition?", "options": ["v-if", "v-for", "v-show", "v-bind"], "answer": "v-if", techStack: 	"vue" },
  { "question": "Two-way binding?", "options": ["v-model", "v-bind", "v-data", "v-sync"], "answer": "v-model", techStack: "vue" },
  { "question": "Vue file extension?", "options": [".vue", ".js", ".html", ".jsx"], "answer": ".vue", techStack: "vue" },
  { "question": "Method section used for?", "options": ["Functions", "Data", "Style", "Routing"], "answer": "Functions", techStack: 	"vue" },
  { "question": "Data in Vue is?", "options": ["Reactive", "Static", "Hidden", "Global"], "answer": "Reactive", techStack: 	"vue" },
  { "question": "Vue CLI is used for?", "options": ["Project setup", "DB", "Testing", "Styling"], "answer": "Project setup", techStack: 	"vue" },
  { "question": "Props used for?", "options": ["Parent → Child data", "Child → Parent", "Global data", "CSS"], "answer": "Parent → Child data", techStack: "vue" },
  { "question": "Event emit used for?", "options": ["Child → Parent", "Parent → Child", "Routing", "State"], "answer": "Child → Parent", techStack: "vue" },
  { "question": "Computed properties are?", "options": ["Cached", "Async", "Static", "Private"], "answer": "Cached", techStack: 	"vue" },
  { "question": "Watchers used for?", "options": ["Observe changes", "Routing", "State", "DB"], "answer": "Observe changes", techStack: 	"vue" },
  { "question": "Vue Router is used for?", "options": ["Navigation", "DB", "Testing", "Auth"], "answer": "Navigation", techStack: 	"vue" },
  { "question": "Vuex is used for?", "options": ["State management", "Routing", "DB", "UI"], "answer": "State management", techStack: "vue" },
  { "question": "v-show vs v-if difference?", "options": ["Display vs render", "Same", "Data binding", "Events"], "answer": "Display vs render", techStack: 	"vue" },
  { "question": "Slot used for?", "options": ["Content distribution", "DB", "Loop", "Auth"], "answer": "Content distribution", techStack: 	"vue" },
  { "question": "Lifecycle hook example?", "options": ["mounted", "start", "boot", "init"], "answer": "mounted", techStack: 	"vue" },
  { "question": "Directive for events?", "options": ["v-on", "v-bind", "v-if", "v-for"], "answer": "v-on", techStack: 	"vue" },
  { "question": "Shorthand for v-bind?", "options": [":", "@", "#", "$"], "answer": ":", techStack: "vue" },
  { "question": "Shorthand for v-on?", "options": ["@", "!", "#", "$"], "answer": "@", techStack: "vue" },
  { "question": "Template section used for?", "options": ["HTML", "CSS", "JS", "Data"], "answer": "HTML", techStack: 	"vue" },
  { "question": "Style section used for?", "options": ["CSS", "JS", "HTML", "Data"], "answer": "CSS", techStack: 	"vue" },
  { "question": "Script section used for?", "options": ["Logic", "Style", "HTML", "Routing"], "answer": "Logic", techStack: 	"vue" },
  { "question": "Vue supports?", "options": ["Component based", "Only pages", "Only functions", "Only classes"], "answer": "Component based", techStack: "vue" },
  { "question": "Ref used for?", "options": ["DOM access", "Routing", "DB", "Events"], "answer": "DOM access", techStack: 	"vue" },
  { "question": "Key attribute used for?", "options": ["List rendering", "Auth", "Data", "Routing"], "answer": "List rendering", techStack: 	"vue" },
  { "question": "Vue is maintained by?", "options": ["Evan You", "Google", "Facebook", "Microsoft"], "answer": "Evan You", techStack: 	"vue" }
];

const questionsFlutter = [
  { "question": "Flutter is developed by?", "options": ["Google", "Apple", "Microsoft", "Meta"], "answer": "Google", techStack: "flutter" },
  { "question": "Flutter uses which language?", "options": ["Dart", "Java", "Kotlin", "Swift"], "answer": "Dart", techStack: "flutter" },
  { "question": "UI in Flutter built using?", "options": ["Widgets", "HTML", "XML", "Views"], "answer": "Widgets", techStack: "flutter" },
  { "question": "Everything in Flutter is?", "options": ["Widget", "Class", "Object", "Component"], "answer": "Widget", techStack: 	"flutter" },
  { "question": "StatelessWidget means?", "options": ["No state", "Mutable state", "DB", "API"], "answer": "No state", techStack: 	"flutter" },
  { "question": "StatefulWidget means?", "options": ["Has state", "No UI", "Static", "Immutable"], "answer":	"Has state", techStack: 	"flutter" },
  { "question": "Hot reload is used for?", "options": ["Fast updates", "Security", "DB", "Testing"], "answer": "Fast updates", techStack: "flutter" },
  { "question": "Main function in Flutter?", "options": ["runApp()", "startApp()", "mainApp()", "initApp()"], "answer": "runApp()", techStack: "flutter" },
  { "question": "MaterialApp provides?", "options": ["Material Design", "Database", "Routing", "Testing"], "answer": "Material Design", techStack: 	"flutter" },
  { "question": "Scaffold provides?", "options": ["Page structure", "DB", "Auth", "State"], "answer": "Page structure", techStack: 	"flutter" },
  { "question": "setState() used for?", "options": ["Update UI", "DB", "Auth", "Routing"], "answer":	"Update UI", techStack: 	"flutter" },
  { "question": "Flutter supports?", "options": ["Cross-platform", "Only Android", "Only iOS", "Only Web"], "answer": "Cross-platform", techStack: "flutter" },
  { "question": "Navigator used for?", "options": ["Routing", "DB", "State", "UI"], "answer": "Routing", techStack: "flutter" },
  { "question": "pubspec.yaml contains?", "options": ["Dependencies", "Code", "UI", "DB"], "answer": "Dependencies", techStack: 	"flutter" },
  { "question": "GestureDetector used for?", "options": ["User input", "DB", "Auth", "Routing"], "answer": "User input", techStack: 	"flutter" },
  { "question": "Expanded widget used for?", "options": ["Flex layout", "Auth", "Routing", "DB"], "answer": "Flex layout", techStack: 	"flutter" },
  { "question": "Column widget arranges?", "options": ["Vertically", "Horizontally", "Grid", "Stack"], "answer": "Vertically", techStack: "flutter" },
  { "question": "Row widget arranges?", "options": ["Horizontally", "Vertically", "Grid", "Stack"], "answer": "Horizontally", techStack: "flutter" },
  { "question": "Container used for?", "options": ["Styling/layout", "DB", "Auth", "Routing"], "answer": "Styling/layout", techStack: 	"flutter" },
  { "question": "Future used for?", "options": ["Async ops", "UI", "Routing", "DB"], "answer": "Async ops", techStack: 	"flutter" },
  { "question": "Stream used for?", "options": ["Continuous data", "Single data", "UI", "DB"], "answer":	"Continuous data", techStack: 	"flutter" },
  { "question": "Flutter engine written in?", "options": ["C++", "Java", "Dart", "Python"], "answer": "C++", techStack: "flutter" },
  { "question": "SafeArea used for?", "options": ["Avoid notches", "DB", "Auth", "Routing"], "answer": "Avoid notches", techStack: "flutter" },
  { "question": "ThemeData used for?", "options": ["App theme", "DB", "State", "Routing"], "answer": "App theme", techStack: 	"flutter" },
  { "question": "ListView used for?", "options": ["Scrollable list", "DB", "Auth", "Routing"], "answer": "Scrollable list", techStack: 	"flutter" },
  { "question": "Flutter web supports?", "options": ["Yes", "No", "Only Android", "Only iOS"], "answer":	"Yes", techStack: 	"flutter" },
  { "question": "Which widget shows text?", "options": ["Text", "Label", "Span", "Paragraph"], "answer": "Text", techStack: "flutter" },
  { "question": "Icon widget used for?", "options": ["Icons", "Images", "Text", "Buttons"], "answer": "Icons", techStack: "flutter" },
  { "question": "Image widget used for?", "options": ["Images", "Text", "Icons", "DB"], "answer": "Images", techStack: 	"flutter" },
  { "question": "Flutter apps compiled to?", "options": ["Native code", "Java bytecode", "JS", "Python"], "answer": "Native code", techStack: 	"flutter" }
];

const questionsDotnet = [
  { "question": ".NET is developed by?", "options": ["Microsoft", "Google", "Apple", "IBM"], "answer": "Microsoft", techStack: "dotnet" },
  { "question": "C# is used in?", "options": [".NET", "Spring", "Django", "Node"], "answer": ".NET", techStack: "dotnet" },
  { "question": "ASP.NET used for?", "options": ["Web apps", "Mobile apps", "DB", "AI"], "answer": "Web apps", techStack: "dotnet" },
  { "question": "CLR stands for?", "options": ["Common Language Runtime", "Code Logic Run", "Central Logic Runtime", "Common Link Runtime"], "answer": "Common Language Runtime", techStack: 	"dotnet" },
  { "question": "Namespace organizes?", "options": ["Code", "DB", "UI", "Security"], "answer":	"Code", techStack: 	"dotnet" },
  { "question":	"Main file extension in C#?",	"options": [".cs", ".net", ".csharp", ".cpp"],	"answer": ".cs", techStack: 	"dotnet"  },
  { "question": "Which keyword creates object?", "options": ["new", "create", "init", "make"], "answer": "new", techStack: "dotnet" },
  { "question": "ASP.NET Core is?", "options": ["Cross-platform", "Only Windows", "Only Web", "Only DB"], "answer": "Cross-platform", techStack: "dotnet" },
  { "question": "MVC stands for?", "options": ["Model View Controller", "Main View Code", "Module View Config", "Model Value Control"], "answer": "Model View Controller", techStack: 	"dotnet" },
  { "question": "Entity Framework used for?", "options": ["ORM", "UI", "Routing", "Security"], "answer": "ORM", techStack: 	"dotnet" },
  { "question": "LINQ used for?", "options": ["Data queries", "UI", "Routing", "Auth"], "answer":	"Data queries", techStack: 	"dotnet" },
  { "question": "Which server runs ASP.NET?", "options": ["Kestrel", "Tomcat", "Nginx", "Apache"], "answer": "Kestrel", techStack: "dotnet" },
  { "question": "Middleware used for?", "options": ["Request pipeline", "UI", "DB", "Auth"], "answer": "Request pipeline", techStack: "dotnet" },
  { "question": "Controller handles?", "options": ["Requests", "DB", "UI", "CSS"], "answer": "Requests", techStack: 	"dotnet" },
  { "question": "Razor used for?", "options": ["Views", "DB", "Routing", "Security"], "answer": "Views", techStack: 	"dotnet" },
  { "question": "appsettings.json stores?", "options": ["Config", "Code", "UI", "DB"], "answer":	"Config", techStack: 	"dotnet" },
  { "question": "NuGet is?", "options": ["Package manager", "DB", "Server", "Framework"], "answer": "Package manager", techStack: "dotnet" },
  { "question": "ActionResult returns?", "options": ["Response", "DB", "UI", "Auth"], "answer": "Response", techStack: "dotnet" },
  { "question": "Dependency Injection supported?", "options": ["Yes", "No", "Only JS", "Only DB"], "answer": "Yes", techStack: 	"dotnet" },
  { "question": "Blazor used for?", "options": ["Web UI with C#", "DB", "Security", "AI"], "answer": "Web UI with C#", techStack: 	"dotnet" },
  { "question": "SignalR used for?", "options": ["Real-time apps", "DB", "Routing", "UI"], "answer":	"Real-time apps", techStack: 	"dotnet" },
  { "question": "Route attribute used for?", "options": ["URL mapping", "DB", "UI", "Auth"], "answer": "URL mapping", techStack: "dotnet" },
  { "question": "Model represents?", "options": ["Data", "UI", "Route", "Server"], "answer": "Data", techStack: 	"dotnet" },
  { "question": "View represents?", "options": ["UI", "Data", "Route", "Server"], "answer": "UI", techStack: 	"dotnet" },
  { "question": "Controller connects?", "options": ["Model & View", "UI & DB", "Route & Server", "Auth & DB"], "answer": "Model & View", techStack: 	"dotnet" },
  { "question": "Which DB works with .NET?", "options": ["All", "Only MySQL", "Only MongoDB", "Only Oracle"], "answer":	"All", techStack: 	"dotnet" },
  { "question": "Async keyword used for?", "options": ["Asynchronous code", "UI", "DB", "Routing"], "answer": "Asynchronous code", techStack: "dotnet" },
  { "question": "Task represents?", "options": ["Async operation", "UI", "DB", "Auth"], "answer": "Async operation", techStack: "dotnet" },
  { "question": "Web API used for?", "options": ["REST services", "UI", "DB", "Auth"], "answer": "REST services", techStack: 	"dotnet" },
  { "question": ".NET supports OOP?", "options": ["Yes", "No", "Only partly", "Only UI"], "answer": "Yes", techStack: 	"dotnet" }
];


async function seedQuestions() {
  try {
    await AptitudeQuestion.deleteMany();

    const rawQuestions = [
  questionsHtml,
  questionsCss,
  questionsJS,
  questionsReact,
  questionsAngular,
  questionsVue,
  questionsCSharp,
  questionsGo,
  questionsNodeJs,
  questionsJava,
  questionsPython,
  questionsDotnet,
  questionsSpring,
  questionsDjango,
  questionsCPlusPlus,
  questionsFlutter,
  questionsTypescript,
  questionsSql,
  questionsNosql,
  questionsRust,
  questionsKotlin,
  questionsSwift,
];

// 🔥 Flatten safely
const allQuestions = rawQuestions.flatMap((set, setIndex) => {
  if (!Array.isArray(set)) {
    console.log(`❌ Dataset at index ${setIndex} is not array`, set);
    return [];
  }

  return set.map((q, i) => {
    if (!q || !q.question) {
      console.log(`❌ Invalid question at set ${setIndex} index ${i}`, q);
      return null;
    }

    return {
      question: q.question,
      options: q.options,
      answer: q.answer,
      marks: q.marks || 1,
      techStack: (q.techStack || "general").toLowerCase().replace(/\s+/g, "")
    };
  }).filter(Boolean);
});



    await AptitudeQuestion.insertMany(allQuestions);

    console.log(" MCQs Inserted Successfully!");
    process.exit();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}


seedQuestions();
